version: "3"
services:
  app:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11725605/yeonseoko:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=mongodb+srv://admin:YGTTagFKZG5NxsJ3@cluster0.zxfdzx0.mongodb.net/coffeechat_ys?retryWrites=true&w=majority
